name: bremen_traffic
description: Bremen Traffic Alerts App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.1.0

flutter:
  uses-material-design: true
